### ISSUE TITLE
tagbot: command not found

### ISSUE THREAD

**Issue by dougbutner** [emre/tagbot#18]
I was able to install via pip, but when I try to run, I get `-bash: tagbot: command not found`

I also tried running `POSTING_KEY=XXXXXXCXXCXCRealKEyXCXCXCXCXXXXXXX hive_tagbot ./config.json`

and got 
`-bash: hive_tagbot: command not found`

I'm new to Python, so I may be missing something simple. Also on the M1 Max processor,

**Comment by dougbutner** [comment]
Got a little further, I think, now held up here: `bot.py: error: unrecognized arguments: tagbot/config.json`

It seems like maybe the README doesn't show the right way to pass in the config file? or it has to be named something else? 

I named mine config.json and have tried putting it all over the directory structure to no effect, and also tried passing in with quotes

Again, apologize I am very new to Python and probably making rookie mistakes.

Edit: I was trying to run the bot.py file, the only thing that seemed to work, like this 

python3 tagbot/bot.py POSTING_KEY=XXXXX tagbot/config.json

**Comment by dougbutner** [comment]
I was able to get the bot to run using `python3 bot.py config.json` in the directory holding both bot.py and a config file

**Comment by dougbutner** [comment]
Now I am getting these errors

```
ERROR:hivebase.http_client:Unexpected exception! Please report at https://github.com/pharesim/hive-python/issues -- RPCError: unspecified error from api.hive.blog (Method not found) in get_account_history
Traceback (most recent call last):
  File "bot.py", line 285, in <module>
    main()
  File "bot.py", line 281, in main
    upvote_bot.run()
  File "bot.py", line 269, in run
    self.start_voting_round()
  File "bot.py", line 145, in start_voting_round
    already_voted_accounts, already_voted_posts = self.last_voted_accounts_and_posts()
  File "bot.py", line 54, in last_voted_accounts_and_posts
    for vote in account.history_reverse(filter_by=["vote"]):
  File "/Users/fresh/Library/Python/3.6/lib/python/site-packages/hive/account.py", line 351, in history_reverse
    start_index = self.virtual_op_count()
  File "/Users/fresh/Library/Python/3.6/lib/python/site-packages/hive/account.py", line 183, in virtual_op_count
    last_item = self.hived.get_account_history(self.name, -1, 0)[0][0]
  File "/Users/fresh/Library/Python/3.6/lib/python/site-packages/hive/hived.py", line 620, in get_account_history
    api='database_api')
  File "/Users/fresh/Library/Python/3.6/lib/python/site-packages/hivebase/http_client.py", line 321, in call
    raise e
  File "/Users/fresh/Library/Python/3.6/lib/python/site-packages/hivebase/http_client.py", line 296, in call
    raise RPCError(detail)
hivebase.exceptions.RPCError: unspecified error from api.hive.blog (Method not found) in get_account_history

```
